replicaCount: 1

image:
  repository: registry.k8s.io/metrics-server/metrics-server
  tag: v0.7.0
  pullPolicy: IfNotPresent

args:
  - --cert-dir=/tmp
  - --secure-port=4443
  - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
  - --kubelet-insecure-tls
  - --metric-resolution=15s

volumeMounts:
  - name: tmp-dir
    mountPath: /tmp

volumes:
  - name: tmp-dir
    emptyDir: {}

resources:
  requests:
    cpu: 100m
    memory: 200Mi
  limits:
    cpu: 200m
    memory: 300Mi

nodeSelector: {}

tolerations: []

affinity: {}

securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 2000