replicaCount: 1

image:
  repository: k8s.gcr.io/metrics-server/metrics-server
  tag: v0.6.3
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 443

resources:
  requests:
    cpu: 100m
    memory: 200Mi
  limits:
    cpu: 200m
    memory: 300Mi