apiVersion: v1
kind: Service
metadata:
  name: metrics-server
spec:
  selector:
    app: metrics-server
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 4443
  type: {{ .Values.service.type }}
